# Generated by Django 5.2 on 2025-05-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(default='API', max_length=50)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('local_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('api_hash', models.CharField(editable=False, max_length=255)),
                ('version_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('editor', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('version_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posthistory_set', to='posts.post')),
            ],
        ),
    ]
