# Generated by Django 5.2 on 2025-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posthistory_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthistory',
            name='last_edited_by',
            field=models.CharField(default=''),
        ),
    ]
