# Generated by Django 5.2 on 2025-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posthistory_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edited_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='editor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='last_edited_by',
            field=models.CharField(default='API'),
        ),
    ]
