# Generated by Django 5.2 on 2025-05-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_last_edited_by_alter_posthistory_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthistory',
            name='last_edited_by',
        ),
    ]
