# Generated by Django 5.2 on 2025-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_posthistory_last_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthistory',
            name='last_edited_by',
            field=models.CharField(default=''),
        ),
    ]
