# Generated by Django 5.2 on 2025-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posthistory_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='last_edited_by',
            field=models.CharField(default='API'),
        ),
    ]
