# Generated by Django 5.2 on 2025-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posthistory_last_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthistory',
            name='last_edited_by',
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='editor',
            field=models.CharField(default='API', max_length=50),
        ),
    ]
